set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name gclk_0 -waveform {0.000 10.000} [get_ports clk]

set_property PACKAGE_PIN V12 [get_ports uart_tx]
set_property PACKAGE_PIN W12 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]

set_property PACKAGE_PIN J17 [get_ports mdio1_mdc]
set_property PACKAGE_PIN J16 [get_ports mdio1_mdio_io]
set_property PACKAGE_PIN L18 [get_ports {phy1_rst_n[0]}]
set_property PACKAGE_PIN J18 [get_ports {rgmii1_rd[0]}]
set_property PACKAGE_PIN K18 [get_ports {rgmii1_rd[1]}]
set_property PACKAGE_PIN J15 [get_ports {rgmii1_rd[2]}]
set_property PACKAGE_PIN K15 [get_ports {rgmii1_rd[3]}]
set_property PACKAGE_PIN K20 [get_ports rgmii1_rx_ctl]
set_property PACKAGE_PIN K19 [get_ports rgmii1_rxc]
set_property PACKAGE_PIN N17 [get_ports {rgmii1_td[0]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii1_td[1]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii1_td[2]}]
set_property PACKAGE_PIN N20 [get_ports {rgmii1_td[3]}]
set_property PACKAGE_PIN R20 [get_ports rgmii1_tx_ctl]
set_property PACKAGE_PIN R21 [get_ports rgmii1_txc]

set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio1_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {phy1_rst_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[3]}]
