set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 20.000 -name gclk_0 -waveform {0.000 10.000} [get_ports clk]

set_property PACKAGE_PIN V12 [get_ports uart_tx]
set_property PACKAGE_PIN W12 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]

set_property PACKAGE_PIN A17 [get_ports reset_n_in]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n_in]

set_property PACKAGE_PIN J18 [get_ports {rgmii1_rd[0]}]
set_property PACKAGE_PIN K18 [get_ports {rgmii1_rd[1]}]
set_property PACKAGE_PIN J15 [get_ports {rgmii1_rd[2]}]
set_property PACKAGE_PIN K15 [get_ports {rgmii1_rd[3]}]
set_property PACKAGE_PIN K20 [get_ports rgmii1_rx_ctl]
set_property PACKAGE_PIN K19 [get_ports rgmii1_rxc]
set_property PACKAGE_PIN N17 [get_ports {rgmii1_td[0]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii1_td[1]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii1_td[2]}]
set_property PACKAGE_PIN N20 [get_ports {rgmii1_td[3]}]
set_property PACKAGE_PIN R20 [get_ports rgmii1_tx_ctl]
set_property PACKAGE_PIN R21 [get_ports rgmii1_txc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]

set_property PACKAGE_PIN P18 [get_ports {rgmii2_rd[0]}]
set_property PACKAGE_PIN P22 [get_ports {rgmii2_rd[1]}]
set_property PACKAGE_PIN N22 [get_ports {rgmii2_rd[2]}]
set_property PACKAGE_PIN M21 [get_ports {rgmii2_rd[3]}]
set_property PACKAGE_PIN P17 [get_ports rgmii2_rx_ctl]
set_property PACKAGE_PIN M19 [get_ports rgmii2_rxc]
set_property PACKAGE_PIN L18 [get_ports {rgmii2_td[0]}]
set_property PACKAGE_PIN L22 [get_ports {rgmii2_td[1]}]
set_property PACKAGE_PIN L21 [get_ports {rgmii2_td[2]}]
set_property PACKAGE_PIN L16 [get_ports {rgmii2_td[3]}]
set_property PACKAGE_PIN M22 [get_ports rgmii2_tx_ctl]
set_property PACKAGE_PIN K16 [get_ports rgmii2_txc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txc]

set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[0]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[1]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[2]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[3]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[4]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[5]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[6]}]
set_property MARK_DEBUG true [get_nets {top_axi_inst/axis_data_fifo_0_tx/s_axis_tdata[7]}]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/m_axis_tlast]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/m_axis_tready]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/m_axis_tvalid]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/s_axis_tlast]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/s_axis_tready]
set_property MARK_DEBUG true [get_nets top_axi_inst/axis_data_fifo_0_tx/s_axis_tvalid]
connect_debug_port u_ila_0/clk [get_nets [list top_axi_inst/mmcm_inst/inst/clk_out3]]


set_property MARK_DEBUG true [get_nets top_axi_inst/fifo_matrix_tx_wea]
set_property MARK_DEBUG true [get_nets top_axi_inst/fifo_matrix_tx_progress]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[0]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[1]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[2]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[3]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[4]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[5]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[6]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[7]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[8]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[9]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[10]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[11]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[12]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[13]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[14]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[15]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[16]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[17]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[18]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[19]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[20]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[21]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[22]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[23]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[24]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[25]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[26]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[27]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[28]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[29]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[30]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[31]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[0]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[1]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[2]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[3]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[4]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[5]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[6]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[7]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[8]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[9]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[10]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[11]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[12]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[13]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[14]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[15]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[16]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[17]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[18]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[19]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[20]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[21]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[22]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[23]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[24]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[25]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[26]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[27]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[28]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[29]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[30]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[31]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[32]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[33]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[34]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[35]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[36]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[37]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[38]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[39]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[40]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[41]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[42]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[43]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[44]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[45]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[46]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[47]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_axi_inst/port_inst_0/rx_outbound_counter[0]} {top_axi_inst/port_inst_0/rx_outbound_counter[1]} {top_axi_inst/port_inst_0/rx_outbound_counter[2]} {top_axi_inst/port_inst_0/rx_outbound_counter[3]} {top_axi_inst/port_inst_0/rx_outbound_counter[4]} {top_axi_inst/port_inst_0/rx_outbound_counter[5]} {top_axi_inst/port_inst_0/rx_outbound_counter[6]} {top_axi_inst/port_inst_0/rx_outbound_counter[7]} {top_axi_inst/port_inst_0/rx_outbound_counter[8]} {top_axi_inst/port_inst_0/rx_outbound_counter[9]} {top_axi_inst/port_inst_0/rx_outbound_counter[10]} {top_axi_inst/port_inst_0/rx_outbound_counter[11]} {top_axi_inst/port_inst_0/rx_outbound_counter[12]} {top_axi_inst/port_inst_0/rx_outbound_counter[13]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {top_axi_inst/port_inst_0/rx_outbound_port_id[0]} {top_axi_inst/port_inst_0/rx_outbound_port_id[1]} {top_axi_inst/port_inst_0/rx_outbound_port_id[2]} {top_axi_inst/port_inst_0/rx_outbound_port_id[3]} {top_axi_inst/port_inst_0/rx_outbound_port_id[4]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[0]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[1]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[2]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[3]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[4]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[5]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[6]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[7]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[8]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[9]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[10]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[11]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[12]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[13]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {top_axi_inst/port_inst_0/rx_saved_ipv4_out[0]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[1]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[2]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[3]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[4]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[5]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[6]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[7]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[0]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[1]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[2]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[3]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[4]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[5]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[6]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[7]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[8]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[9]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[10]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[11]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[12]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[13]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[14]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[15]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[16]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[17]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[18]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[19]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[20]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[21]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[22]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[23]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[24]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[25]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[26]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[27]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[28]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[29]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[30]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[31]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[0]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[1]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[2]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[3]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[4]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[5]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[6]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[7]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[8]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[9]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[10]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[11]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[12]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[13]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[14]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[15]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[16]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[17]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[18]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[19]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[20]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[21]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[22]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[23]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[24]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[25]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[26]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[27]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[28]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[29]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[30]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[31]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[32]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[33]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[34]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[35]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[36]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[37]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[38]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[39]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[40]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[41]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[42]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[43]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[44]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[45]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[46]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[47]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_axi_inst/port_inst_1/rx_outbound_counter[0]} {top_axi_inst/port_inst_1/rx_outbound_counter[1]} {top_axi_inst/port_inst_1/rx_outbound_counter[2]} {top_axi_inst/port_inst_1/rx_outbound_counter[3]} {top_axi_inst/port_inst_1/rx_outbound_counter[4]} {top_axi_inst/port_inst_1/rx_outbound_counter[5]} {top_axi_inst/port_inst_1/rx_outbound_counter[6]} {top_axi_inst/port_inst_1/rx_outbound_counter[7]} {top_axi_inst/port_inst_1/rx_outbound_counter[8]} {top_axi_inst/port_inst_1/rx_outbound_counter[9]} {top_axi_inst/port_inst_1/rx_outbound_counter[10]} {top_axi_inst/port_inst_1/rx_outbound_counter[11]} {top_axi_inst/port_inst_1/rx_outbound_counter[12]} {top_axi_inst/port_inst_1/rx_outbound_counter[13]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {top_axi_inst/port_inst_1/rx_outbound_port_id[0]} {top_axi_inst/port_inst_1/rx_outbound_port_id[1]} {top_axi_inst/port_inst_1/rx_outbound_port_id[2]} {top_axi_inst/port_inst_1/rx_outbound_port_id[3]} {top_axi_inst/port_inst_1/rx_outbound_port_id[4]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[0]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[1]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[2]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[3]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[4]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[5]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[6]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[7]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[8]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[9]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[10]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[11]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[12]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[13]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {top_axi_inst/port_inst_1/rx_saved_ipv4_out[0]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[1]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[2]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[3]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[4]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[5]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[6]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[7]}]]
connect_debug_port u_ila_0/probe21 [get_nets [list top_axi_inst/port_inst_1/arp_written]]
connect_debug_port u_ila_0/probe22 [get_nets [list top_axi_inst/port_inst_0/arp_written]]
connect_debug_port u_ila_0/probe23 [get_nets [list top_axi_inst/port_inst_0/ip_lookup_routing]]
connect_debug_port u_ila_0/probe24 [get_nets [list top_axi_inst/port_inst_1/ip_lookup_routing]]
connect_debug_port u_ila_0/probe27 [get_nets [list top_axi_inst/port_inst_0/ip_routing]]
connect_debug_port u_ila_0/probe28 [get_nets [list top_axi_inst/port_inst_1/ip_routing]]
connect_debug_port u_ila_0/probe32 [get_nets [list top_axi_inst/port_inst_0/rx_found_nexthop_ipv4]]
connect_debug_port u_ila_0/probe33 [get_nets [list top_axi_inst/port_inst_1/rx_found_nexthop_ipv4]]
connect_debug_port u_ila_0/probe36 [get_nets [list top_axi_inst/port_inst_1/rx_outbound]]
connect_debug_port u_ila_0/probe37 [get_nets [list top_axi_inst/port_inst_0/rx_outbound]]
connect_debug_port u_ila_0/probe40 [get_nets [list top_axi_inst/port_inst_0/rx_saved_ipv4_wen]]
connect_debug_port u_ila_0/probe41 [get_nets [list top_axi_inst/port_inst_1/rx_saved_ipv4_wen]]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list top_axi_inst/mmcm_inst_1/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[0]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[1]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[2]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[3]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[4]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[5]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[6]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[7]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[8]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[9]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[10]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[11]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[12]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[13]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[14]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[15]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[16]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[17]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[18]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[19]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[20]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[21]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[22]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[23]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[24]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[25]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[26]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[27]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[28]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[29]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[30]} {top_axi_inst/port_inst_0/rx_nexthop_ipv4_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 48 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[0]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[1]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[2]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[3]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[4]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[5]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[6]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[7]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[8]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[9]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[10]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[11]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[12]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[13]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[14]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[15]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[16]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[17]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[18]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[19]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[20]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[21]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[22]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[23]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[24]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[25]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[26]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[27]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[28]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[29]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[30]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[31]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[32]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[33]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[34]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[35]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[36]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[37]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[38]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[39]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[40]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[41]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[42]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[43]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[44]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[45]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[46]} {top_axi_inst/port_inst_0/rx_nexthop_mac_addr[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_axi_inst/port_inst_0/rx_nexthop_port[0]} {top_axi_inst/port_inst_0/rx_nexthop_port[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 14 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {top_axi_inst/port_inst_0/rx_outbound_counter[0]} {top_axi_inst/port_inst_0/rx_outbound_counter[1]} {top_axi_inst/port_inst_0/rx_outbound_counter[2]} {top_axi_inst/port_inst_0/rx_outbound_counter[3]} {top_axi_inst/port_inst_0/rx_outbound_counter[4]} {top_axi_inst/port_inst_0/rx_outbound_counter[5]} {top_axi_inst/port_inst_0/rx_outbound_counter[6]} {top_axi_inst/port_inst_0/rx_outbound_counter[7]} {top_axi_inst/port_inst_0/rx_outbound_counter[8]} {top_axi_inst/port_inst_0/rx_outbound_counter[9]} {top_axi_inst/port_inst_0/rx_outbound_counter[10]} {top_axi_inst/port_inst_0/rx_outbound_counter[11]} {top_axi_inst/port_inst_0/rx_outbound_counter[12]} {top_axi_inst/port_inst_0/rx_outbound_counter[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 14 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {top_axi_inst/port_inst_0/rx_outbound_length[0]} {top_axi_inst/port_inst_0/rx_outbound_length[1]} {top_axi_inst/port_inst_0/rx_outbound_length[2]} {top_axi_inst/port_inst_0/rx_outbound_length[3]} {top_axi_inst/port_inst_0/rx_outbound_length[4]} {top_axi_inst/port_inst_0/rx_outbound_length[5]} {top_axi_inst/port_inst_0/rx_outbound_length[6]} {top_axi_inst/port_inst_0/rx_outbound_length[7]} {top_axi_inst/port_inst_0/rx_outbound_length[8]} {top_axi_inst/port_inst_0/rx_outbound_length[9]} {top_axi_inst/port_inst_0/rx_outbound_length[10]} {top_axi_inst/port_inst_0/rx_outbound_length[11]} {top_axi_inst/port_inst_0/rx_outbound_length[12]} {top_axi_inst/port_inst_0/rx_outbound_length[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 5 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {top_axi_inst/port_inst_0/rx_outbound_port_id[0]} {top_axi_inst/port_inst_0/rx_outbound_port_id[1]} {top_axi_inst/port_inst_0/rx_outbound_port_id[2]} {top_axi_inst/port_inst_0/rx_outbound_port_id[3]} {top_axi_inst/port_inst_0/rx_outbound_port_id[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 14 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[0]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[1]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[2]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[3]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[4]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[5]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[6]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[7]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[8]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[9]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[10]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[11]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[12]} {top_axi_inst/port_inst_0/rx_saved_ipv4_addr[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {top_axi_inst/port_inst_0/rx_saved_ipv4_in[0]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[1]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[2]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[3]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[4]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[5]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[6]} {top_axi_inst/port_inst_0/rx_saved_ipv4_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {top_axi_inst/port_inst_0/rx_saved_ipv4_out[0]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[1]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[2]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[3]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[4]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[5]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[6]} {top_axi_inst/port_inst_0/rx_saved_ipv4_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[0]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[1]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[2]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[3]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[4]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[5]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[6]} {top_axi_inst/axis_data_fifo_0_tx/m_axis_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 32 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[0]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[1]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[2]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[3]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[4]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[5]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[6]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[7]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[8]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[9]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[10]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[11]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[12]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[13]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[14]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[15]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[16]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[17]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[18]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[19]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[20]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[21]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[22]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[23]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[24]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[25]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[26]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[27]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[28]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[29]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[30]} {top_axi_inst/port_inst_1/rx_nexthop_ipv4_addr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 48 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[0]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[1]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[2]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[3]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[4]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[5]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[6]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[7]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[8]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[9]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[10]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[11]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[12]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[13]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[14]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[15]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[16]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[17]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[18]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[19]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[20]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[21]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[22]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[23]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[24]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[25]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[26]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[27]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[28]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[29]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[30]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[31]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[32]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[33]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[34]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[35]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[36]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[37]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[38]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[39]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[40]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[41]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[42]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[43]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[44]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[45]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[46]} {top_axi_inst/port_inst_1/rx_nexthop_mac_addr[47]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 2 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {top_axi_inst/port_inst_1/rx_nexthop_port[0]} {top_axi_inst/port_inst_1/rx_nexthop_port[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 14 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {top_axi_inst/port_inst_1/rx_outbound_counter[0]} {top_axi_inst/port_inst_1/rx_outbound_counter[1]} {top_axi_inst/port_inst_1/rx_outbound_counter[2]} {top_axi_inst/port_inst_1/rx_outbound_counter[3]} {top_axi_inst/port_inst_1/rx_outbound_counter[4]} {top_axi_inst/port_inst_1/rx_outbound_counter[5]} {top_axi_inst/port_inst_1/rx_outbound_counter[6]} {top_axi_inst/port_inst_1/rx_outbound_counter[7]} {top_axi_inst/port_inst_1/rx_outbound_counter[8]} {top_axi_inst/port_inst_1/rx_outbound_counter[9]} {top_axi_inst/port_inst_1/rx_outbound_counter[10]} {top_axi_inst/port_inst_1/rx_outbound_counter[11]} {top_axi_inst/port_inst_1/rx_outbound_counter[12]} {top_axi_inst/port_inst_1/rx_outbound_counter[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 14 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {top_axi_inst/port_inst_1/rx_outbound_length[0]} {top_axi_inst/port_inst_1/rx_outbound_length[1]} {top_axi_inst/port_inst_1/rx_outbound_length[2]} {top_axi_inst/port_inst_1/rx_outbound_length[3]} {top_axi_inst/port_inst_1/rx_outbound_length[4]} {top_axi_inst/port_inst_1/rx_outbound_length[5]} {top_axi_inst/port_inst_1/rx_outbound_length[6]} {top_axi_inst/port_inst_1/rx_outbound_length[7]} {top_axi_inst/port_inst_1/rx_outbound_length[8]} {top_axi_inst/port_inst_1/rx_outbound_length[9]} {top_axi_inst/port_inst_1/rx_outbound_length[10]} {top_axi_inst/port_inst_1/rx_outbound_length[11]} {top_axi_inst/port_inst_1/rx_outbound_length[12]} {top_axi_inst/port_inst_1/rx_outbound_length[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 5 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {top_axi_inst/port_inst_1/rx_outbound_port_id[0]} {top_axi_inst/port_inst_1/rx_outbound_port_id[1]} {top_axi_inst/port_inst_1/rx_outbound_port_id[2]} {top_axi_inst/port_inst_1/rx_outbound_port_id[3]} {top_axi_inst/port_inst_1/rx_outbound_port_id[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 14 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[0]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[1]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[2]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[3]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[4]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[5]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[6]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[7]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[8]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[9]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[10]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[11]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[12]} {top_axi_inst/port_inst_1/rx_saved_ipv4_addr[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 8 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {top_axi_inst/port_inst_1/rx_saved_ipv4_in[0]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[1]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[2]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[3]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[4]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[5]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[6]} {top_axi_inst/port_inst_1/rx_saved_ipv4_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 8 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {top_axi_inst/port_inst_1/rx_saved_ipv4_out[0]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[1]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[2]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[3]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[4]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[5]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[6]} {top_axi_inst/port_inst_1/rx_saved_ipv4_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list top_axi_inst/port_inst_0/arp_write]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list top_axi_inst/port_inst_1/arp_write]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list top_axi_inst/port_inst_0/arp_written]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list top_axi_inst/port_inst_1/arp_written]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list top_axi_inst/fifo_matrix_tx_progress]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list top_axi_inst/fifo_matrix_tx_wea]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list top_axi_inst/port_inst_1/ip_lookup_routing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list top_axi_inst/port_inst_0/ip_lookup_routing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list top_axi_inst/port_inst_0/ip_routed]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list top_axi_inst/port_inst_1/ip_routed]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list top_axi_inst/port_inst_1/ip_routing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list top_axi_inst/port_inst_0/ip_routing]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list top_axi_inst/axis_data_fifo_0_tx/m_axis_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list top_axi_inst/axis_data_fifo_0_tx/m_axis_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list top_axi_inst/axis_data_fifo_0_tx/m_axis_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list top_axi_inst/port_inst_0/rx_found_nexthop_ipv4]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list top_axi_inst/port_inst_1/rx_found_nexthop_ipv4]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list top_axi_inst/port_inst_1/rx_lookup_nexthop_mac]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list top_axi_inst/port_inst_0/rx_lookup_nexthop_mac]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list top_axi_inst/port_inst_0/rx_outbound]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list top_axi_inst/port_inst_1/rx_outbound]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list top_axi_inst/port_inst_0/rx_read]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list top_axi_inst/port_inst_1/rx_read]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list top_axi_inst/port_inst_0/rx_saved_ipv4_wen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list top_axi_inst/port_inst_1/rx_saved_ipv4_wen]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets host_clk]
